from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import (
    DashboardView,
    ExpenseCreateView,
    ExpenseDeleteView,
    ExpenseListView,
    ExpenseUpdateView,
    SaleCreateView,
    SaleDeleteView,
    SaleListView,
    SaleUpdateView,
    ServiceCreateView,
    ServiceDeleteView,
    ServiceListView,
    ServiceUpdateView,
    StaffCreateView,
    StaffDeleteView,
    StaffListView,
    StaffLoginView,
    StaffUpdateView,
    book_now,
    expense_report,
    home,
    sales_report,
)

urlpatterns = [
    path("", home, name="home"),
    path("book/", book_now, name="book-now"),
    path("login/", StaffLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("staff/", StaffListView.as_view(), name="staff-list"),
    path("staff/add/", StaffCreateView.as_view(), name="staff-create"),
    path("staff/<int:pk>/edit/", StaffUpdateView.as_view(), name="staff-update"),
    path("staff/<int:pk>/delete/", StaffDeleteView.as_view(), name="staff-delete"),
    path("services/", ServiceListView.as_view(), name="service-list"),
    path("services/add/", ServiceCreateView.as_view(), name="service-create"),
    path("services/<int:pk>/edit/", ServiceUpdateView.as_view(), name="service-update"),
    path("services/<int:pk>/delete/", ServiceDeleteView.as_view(), name="service-delete"),
    path("sales/", SaleListView.as_view(), name="sale-list"),
    path("sales/add/", SaleCreateView.as_view(), name="sale-create"),
    path("sales/<int:pk>/edit/", SaleUpdateView.as_view(), name="sale-update"),
    path("sales/<int:pk>/delete/", SaleDeleteView.as_view(), name="sale-delete"),
    path("expenses/", ExpenseListView.as_view(), name="expense-list"),
    path("expenses/add/", ExpenseCreateView.as_view(), name="expense-create"),
    path("expenses/<int:pk>/edit/", ExpenseUpdateView.as_view(), name="expense-update"),
    path("expenses/<int:pk>/delete/", ExpenseDeleteView.as_view(), name="expense-delete"),
    path("reports/sales/", sales_report, name="sales-report"),
    path("reports/expenses/", expense_report, name="expense-report"),
]
