from django.contrib.auth.views import (
    LogoutView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path

from .forms import PasswordResetConfirmStyledForm, PasswordResetRequestForm
from .loyalty_views import (
    BarberNoteCreateView,
    BarberNoteListView,
    CustomerDashboardView,
    CustomerListView,
    LoyaltyOwnerReportView,
    SlowHourCreateView,
    SlowHourDeleteView,
    SlowHourUpdateView,
    customer_register,
    loyalty_manage,
)
from .api_views import booking_create, booking_options, public_home
from .views import (
    DashboardView,
    ExpenseCreateView,
    ExpenseDeleteView,
    ExpenseListView,
    ExpenseUpdateView,
    NotificationListView,
    PaymentCreateView,
    PaymentListView,
    SaleChangeRequestListView,
    SaleChangeRequestReviewView,
    SaleCreateView,
    SaleDeleteView,
    SaleListView,
    SaleUpdateView,
    SalaryAdvanceCreateView,
    SalaryAdvanceListView,
    SalaryAdvanceReviewView,
    ServiceCreateView,
    ServiceDeleteView,
    ServiceListView,
    ServiceUpdateView,
    StaffCreateView,
    StaffDeleteView,
    StaffListView,
    StaffLoginView,
    StaffUpdateView,
    book_now,
    expense_report,
    home,
    notification_open,
    sales_report,
)

urlpatterns = [
    path("", home, name="home"),
    path("book/", book_now, name="book-now"),
    path("api/public/home/", public_home, name="api-public-home"),
    path("api/booking/options/", booking_options, name="api-booking-options"),
    path("api/booking/", booking_create, name="api-booking"),
    path("account/register/", customer_register, name="customer-register"),
    path("account/", CustomerDashboardView.as_view(), name="customer-dashboard"),
    path("customers/", CustomerListView.as_view(), name="customer-list"),
    path("customers/<int:customer_pk>/notes/add/", BarberNoteCreateView.as_view(), name="barber-note-add"),
    path("barber/notes/", BarberNoteListView.as_view(), name="barber-notes"),
    path("loyalty/reports/", LoyaltyOwnerReportView.as_view(), name="loyalty-reports"),
    path("loyalty/manage/", loyalty_manage, name="loyalty-manage"),
    path("loyalty/slow-hours/add/", SlowHourCreateView.as_view(), name="slow-hour-create"),
    path("loyalty/slow-hours/<int:pk>/edit/", SlowHourUpdateView.as_view(), name="slow-hour-edit"),
    path("loyalty/slow-hours/<int:pk>/delete/", SlowHourDeleteView.as_view(), name="slow-hour-delete"),
    path("login/", StaffLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "password-reset/",
        PasswordResetView.as_view(
            form_class=PasswordResetRequestForm,
            template_name="shop/password_reset_form.html",
            email_template_name="shop/password_reset_email.txt",
            subject_template_name="shop/password_reset_subject.txt",
            success_url="/password-reset/done/",
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(template_name="shop/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            form_class=PasswordResetConfirmStyledForm,
            template_name="shop/password_reset_confirm.html",
            success_url="/reset/done/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(template_name="shop/password_reset_complete.html"),
        name="password_reset_complete",
    ),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("staff/", StaffListView.as_view(), name="staff-list"),
    path("staff/add/", StaffCreateView.as_view(), name="staff-create"),
    path("staff/<int:pk>/edit/", StaffUpdateView.as_view(), name="staff-update"),
    path("staff/<int:pk>/delete/", StaffDeleteView.as_view(), name="staff-delete"),
    path("services/", ServiceListView.as_view(), name="service-list"),
    path("services/add/", ServiceCreateView.as_view(), name="service-create"),
    path("services/<int:pk>/edit/", ServiceUpdateView.as_view(), name="service-update"),
    path("services/<int:pk>/delete/", ServiceDeleteView.as_view(), name="service-delete"),
    path("sales/", SaleListView.as_view(), name="sale-list"),
    path("sales/add/", SaleCreateView.as_view(), name="sale-create"),
    path("sales/<int:pk>/edit/", SaleUpdateView.as_view(), name="sale-update"),
    path("sales/<int:pk>/delete/", SaleDeleteView.as_view(), name="sale-delete"),
    path("sales/changes/", SaleChangeRequestListView.as_view(), name="sale-change-list"),
    path("sales/changes/<int:pk>/review/", SaleChangeRequestReviewView.as_view(), name="sale-change-review"),
    path("notifications/", NotificationListView.as_view(), name="notifications"),
    path("notifications/<int:pk>/open/", notification_open, name="notification-open"),
    path("expenses/", ExpenseListView.as_view(), name="expense-list"),
    path("expenses/add/", ExpenseCreateView.as_view(), name="expense-create"),
    path("expenses/<int:pk>/edit/", ExpenseUpdateView.as_view(), name="expense-update"),
    path("expenses/<int:pk>/delete/", ExpenseDeleteView.as_view(), name="expense-delete"),
    path("payments/", PaymentListView.as_view(), name="payment-list"),
    path("payments/add/", PaymentCreateView.as_view(), name="payment-create"),
    path("salary-advances/", SalaryAdvanceListView.as_view(), name="salary-advance-list"),
    path("salary-advances/add/", SalaryAdvanceCreateView.as_view(), name="salary-advance-create"),
    path("salary-advances/<int:pk>/review/", SalaryAdvanceReviewView.as_view(), name="salary-advance-review"),
    path("reports/sales/", sales_report, name="sales-report"),
    path("reports/expenses/", expense_report, name="expense-report"),
]
