# Generated by Django 4.2.29 on 2026-04-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Public URL for the service photo.'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_url',
            field=models.URLField(blank=True, help_text="Public URL for this staff member's profile photo."),
        ),
    ]
