# Generated by Django 4.2.29 on 2026-04-02 19:55

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_service_photo_url_user_photo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('referral_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('sms_opt_out', models.BooleanField(default=False)),
                ('points_balance', models.IntegerField(default=0)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='bronze', max_length=20)),
                ('last_visit_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='shop.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.PositiveIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('points_per_visit', models.PositiveIntegerField(default=50)),
                ('points_per_dollar', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6)),
                ('referral_bonus_referrer', models.PositiveIntegerField(default=100)),
                ('referral_bonus_referee', models.PositiveIntegerField(default=50)),
                ('shop_display_name', models.CharField(default='Garden City Fine Cuts', max_length=120)),
                ('booking_base_url', models.URLField(blank=True)),
                ('sms_retention_enabled', models.BooleanField(default=True)),
                ('sms_retention_days', models.PositiveIntegerField(default=21)),
                ('review_request_enabled', models.BooleanField(default=True)),
                ('review_request_hours_after', models.PositiveIntegerField(default=24)),
                ('review_bonus_points', models.PositiveIntegerField(default=25)),
                ('at_risk_days', models.PositiveIntegerField(default=45, help_text='Customers with no visit in this many days are flagged as at-risk.')),
            ],
        ),
        migrations.CreateModel(
            name='SlowHourWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('weekday_start', models.PositiveSmallIntegerField(help_text='0=Monday ... 6=Sunday')),
                ('weekday_end', models.PositiveSmallIntegerField(help_text='Inclusive; same as start for single day.')),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('multiplier', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='staff_snapshot_name',
            field=models.CharField(blank=True, help_text='Preserved if staff account is removed.', max_length=255),
        ),
        migrations.AddField(
            model_name='sale',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='shop.appointment'),
        ),
        migrations.AddField(
            model_name='sale',
            name='staff_snapshot_name',
            field=models.CharField(blank=True, help_text='Preserved if staff account is removed.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sale',
            name='staff',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'manager', 'staff']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('customer', 'Customer')], default='staff', max_length=20),
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('message_body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='shop.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewNudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(default='sms', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_nudge', to='shop.appointment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.appointment')),
                ('referee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_credit', to='shop.customer')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_paid', to='shop.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PointsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_delta', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('entry_type', models.CharField(choices=[('visit', 'Visit'), ('spend', 'Spend'), ('referral_referrer', 'Referral (Referrer)'), ('referral_referee', 'Referral (New Customer)'), ('review_bonus', 'Review Bonus'), ('adjustment', 'Adjustment')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('multiplier_applied', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.appointment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='shop.customer')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerBarberNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('previous_cut_photo', models.ImageField(blank=True, null=True, upload_to='ledger_cuts/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barber_notes', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_notes', to='shop.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='shop.customer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='shop.customer'),
        ),
    ]
