# Generated by Django 4.2.29 on 2026-04-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_loyalty_and_sale_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltysettings',
            name='retention_sms_template',
            field=models.TextField(default="Hi {first_name}, it's been {weeks} weeks since your last visit at {shop_name}! Book your next fresh cut here: {booking_link}", help_text='Placeholders: {first_name}, {shop_name}, {booking_link}, {weeks}, {retention_days}'),
        ),
        migrations.AddField(
            model_name='loyaltysettings',
            name='review_sms_template',
            field=models.TextField(default='Hi {first_name}, thanks for visiting {shop_name}. Leave a Google or Yelp review — {review_bonus_points} bonus points on your next visit.', help_text='Placeholders: {first_name}, {shop_name}, {review_bonus_points}'),
        ),
    ]
